### ISSUE TITLE
Mini-cwrc-writer: remove popup

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#309]
Sorry if this is a duplicate: it would be nice if, after the first time, there was just a little red reminder "XML only" in the top right of the note panel, as opposed to the popup appearing each and every time a note is created. Popup could reappear with each new session.

**Comment by ilovan** [comment]
I think this is just another facet of  #333. The pop-up shows up not because we cannot add annotations inside the note, but because at the time of the note creation, the text highlighted does not contain any rdf. 

That is not to say we don't have a problem: even after including an RDF entity inside a note, we still get the same message when we edit the note entity, even though the rdf entity we annotated when we created the note is still there.

**Comment by SusanBrown** [comment]
@ajmacdonald I know we've talked about this before. We have to get rid of the  mode popup for the notes somehow, and it would be great to get rid of them also when exiting from direct Edit mode as well. What's the best way of doing this?

**Comment by ilovan** [comment]
@ajmacdonald ,

As you are already working on troubleshooting the mini-CWRC-Writer, maybe it would make sense to tackle this as well? I'm putting it into your "In Progress" pile for now, but do let me know if you think this is a complex issue to fix, as I would not want it to take time from the integration work at this time.

**Comment by ajmacdonald** [comment]
https://github.com/cwrc/CWRC-WriterBase/commit/42fd7c8327c80e89f091919a7c2c4c6ea4fc1720

**Comment by ilovan** [comment]
Works now, no more CWRC-Writer mode pop-up

**Comment by ilovan** [comment]
Confirmed on dev-06 and prod Git-Writer
