### ISSUE TITLE
Fix cwrcEntry.xml

### ISSUE THREAD

**Issue by SusanBrown** [cwrc/DEPRECATED-CWRC-Writer#493]
This template file is not usable because there are no content placeholders. It seems to match what is in the template repo (https://github.com/cwrc/CWRC-Schema/blob/master/templates/cwrc_entry_template.xml) so I think this is for @ilovan to flesh it out in January. 

Mihaela, it might be easier to take an existing CWRC entry and adapt it rather than going the other direction.

**Comment by ilovan** [comment]
Susan, the reason there is no placeholder is because the CWRC schema is much more flexible than the Orlando schema and as such supports wildly different document structures (see CEWW versus Playwrights entries)

There is no such thing as an existing CWRC entry at this point and I don't foresee one anytime soon because it would defeat the purpose of having the schema so flexible if we constrain the structure with the template. 

I know James removed this template from the list of available templates in CWRC-Writer (https://github.com/cwrc/CWRC-Writer/issues/494), but we should probably consider having one that would just reference the CWRC schema and stylesheet, have a very minimal header in place and provide a link to the CWRC schema documentation : http://cwrc.ca/schemas/documentation/CWRC_entry/

Thoughts?
